version: '3'
services:
  mongodb:
    image: mongo
    container_name: kafka_test_db
    ports:
      - "27017:27017"
  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/bitnami/redis/data
  kafka-app:
    container_name: kafka-test
    build: .
    # image: b083bf0f4db0
    ports:
      - "5000:5000"
    volumes:
    - .:/app
    environment:
      GRPC_PORT: :5000
      HTTP_PORT: :8000

    depends_on:
    - "redis"
    - "mongodb"
volumes:
  redis_data:
    driver: local
